name: fgm_lyrics_app
description: "Full Gospel Mission app for browsing and sharing new hymns lyrics, supporting multiple languages and modern UI."
publish_to: 'none'
version: 1.2.0+7

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.2.0
  shared_preferences: ^2.5.5
  path: ^1.9.1
  path_provider: ^2.1.6
  share_plus: ^13.2.1
  flutter_riverpod: ^3.3.2
  flutter_gutter: ^2.2.0
  audioplayers: ^6.8.1
  in_app_purchase: ^3.2.3
  http: ^1.6.0
  url_launcher: ^6.3.2
  upgrader: ^13.5.0
  firebase_core: ^4.12.1
  cloud_firestore: ^6.7.1
  flutter_html: ^3.0.0
  open_file: ^4.0.0
  pdfx: ^2.9.2
  synchronized: ^3.4.1
  lucide_icons_flutter: ^3.1.15
  # google_mobile_ads: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.1.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true # Remove alpha channel for iOS App Store compliance
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#0288D1"
    theme_color: "#0288D1"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"